server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spare_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456 # 请在此处填写你的真实 MySQL root 密码
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.langdong.spare.entity

jwt:
  secret: spare-management-system-secret-key-2024-langdong
  expiration: 86400000
